### ISSUE TITLE
constellation issue : AttributeError: 'Sky' object has no attribute '_constellation_names'

### ISSUE THREAD

**Issue by roumano** [partofthething/ha_skyfield#14]
I'm not able to use constellation 

I set this configuration :  
```
camera:
    platform: ha_skyfield
    show_constellations: true
    constellations_list:
        - UrsaMajor
        - Andromeda
        - Aquarius
        - Aquila
        - Ara
        - Aries
        - Auriga
        - Cancer
        - Capricornus
        - Carina
        - Cassiopeia
        - Centaurus
        - Circinus
        - Cygnus
        - Lynx
        - Lyra
        - Orion
        - Pegasus
        - Sagitta
        - Sagittarius
        - Scorpius
        - Taurus
        - Vela
        - Virgo
```

it's display moon and other Planets but it's not displaying any constellation

after putting the extension in debug mode, i saw this crash :  
```
mai 17 11:59:57 rasp hass[14720]: 2022-05-17 11:59:57 ERROR (MainThread) [aiohttp.server] Error handling request
mai 17 11:59:57 rasp hass[14720]: Traceback (most recent call last):
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
mai 17 11:59:57 rasp hass[14720]:     resp = await request_handler(request)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
mai 17 11:59:57 rasp hass[14720]:     resp = await handler(request)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
mai 17 11:59:57 rasp hass[14720]:     return await handler(request)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
mai 17 11:59:57 rasp hass[14720]:     return await handler(request)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
mai 17 11:59:57 rasp hass[14720]:     return await handler(request)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
mai 17 11:59:57 rasp hass[14720]:     return await handler(request)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 219, in auth_middleware
mai 17 11:59:57 rasp hass[14720]:     return await handler(request)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 137, in handle
mai 17 11:59:57 rasp hass[14720]:     result = await result
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/camera/__init__.py", line 736, in get
mai 17 11:59:57 rasp hass[14720]:     return await self.handle(request, camera)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/camera/__init__.py", line 754, in handle
mai 17 11:59:57 rasp hass[14720]:     image = await _async_get_image(
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/camera/__init__.py", line 174, in _async_get_image
mai 17 11:59:57 rasp hass[14720]:     if image_bytes := await camera.async_camera_image(
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/lib/python3.10/site-packages/homeassistant/components/camera/__init__.py", line 581, in async_camera_image
mai 17 11:59:57 rasp hass[14720]:     return await self.hass.async_add_executor_job(
mai 17 11:59:57 rasp hass[14720]:   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
mai 17 11:59:57 rasp hass[14720]:     result = self.fn(*self.args, **self.kwargs)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/.homeassistant/custom_components/ha_skyfield/camera.py", line 145, in camera_image
mai 17 11:59:57 rasp hass[14720]:     self.sky.load(self._tmpdir)
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/.homeassistant/custom_components/ha_skyfield/bodies.py", line 75, in load
mai 17 11:59:57 rasp hass[14720]:     self._run_initial_computations()
mai 17 11:59:57 rasp hass[14720]:   File "/data/homeassistant/.homeassistant/custom_components/ha_skyfield/bodies.py", line 94, in _run_initial_computations
mai 17 11:59:57 rasp hass[14720]:     self, self._constellation_names
mai 17 11:59:57 rasp hass[14720]: AttributeError: 'Sky' object has no attribute '_constellation_names'
```

It's running on a Rasberry Pi 4 on Debian 10 armv7l
